# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
    - name: Restore dependencies
      run: dotnet restore src/SlowDown/Libexec.AspNetCore.SlowDown.csproj
    - name: Build
      run: dotnet build src/SlowDown/Libexec.AspNetCore.SlowDown.csproj --no-restore

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
    - name: Restore dependencies
      run: dotnet restore test/SlowDown.Tests/SlowDown.Tests.csproj
    - name: Build
      run: dotnet build test/SlowDown.Tests/SlowDown.Tests.csproj --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
